#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('INOX_START', microtime(true));

require __DIR__ . '/core/vendor/autoload.php';

$app = require_once __DIR__ . '/core/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
